new

diff --git a/run b/run
--- a/run
+++ b/run
@@ -103,6 +103,31 @@ then
         fi
     fi
 
+# Login command to run user_auth.js file
+elif [ "$1" = "login" ]; then
+    # TSC=$(tsc main.ts 2>&1 > '/dev/null');
+    TSC=$(npx tsc user_auth.ts 2>&1 > '/dev/null');
+
+    if [[ "${TSC}" != '' ]]; then
+        echo "Files failed to compile"
+        exit 1
+    else
+        if [[ "${LOG_FILE}" == '' ]]; then
+            echo "LOG_FILE not set"
+            exit 1
+        elif [[ "${GITHUB_TOKEN}" == '' ]]; then
+            echo "GITHUB_TOKEN not set"
+            exit 1
+        else
+            node user_auth.js $1
+            exit $?
+        fi
+    fi
+
+
+
+
+
 # invalid input
 else
     echo "Please enter a valid argument: ./run <URL_FILE> ./run test ./run install"
