Created flow with authentication

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,5 +1,8 @@
 #!/bin/bash
+
+
 export $(egrep -v '^#' .env | xargs)
+
 
 # check if input is install
 if [ "$1" = "install" ]; then
@@ -140,6 +143,31 @@ elif  [ "$1" = "logout" ]; then
             exit $?
         fi
     fi
+
+# upload
+elif [ "$1" = "upload" ]; then
+    # TSC=$(tsc main.ts 2>&1 > '/dev/null');
+    TSC=$(npx tsc upload.ts 2>&1 > '/dev/null');
+
+    if [[ "${TSC}" != '' ]]; then
+        echo "Files failed to compile"
+        exit 1
+    else
+        if [[ "${LOG_FILE}" == '' ]]; then
+            echo "LOG_FILE not set"
+            exit 1
+        elif [[ "${GITHUB_TOKEN}" == '' ]]; then
+            echo "GITHUB_TOKEN not set"
+            exit 1
+        else
+            node upload.js $1
+            exit $?
+        fi
+    fi
+
+
+
+
 
 # invalid input
 else
